# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProseAndBabel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProseAndBabel.proto',
  package='proseandbabel',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13ProseAndBabel.proto\x12\rproseandbabel\"\x1b\n\x0cHaikuRequest\x12\x0b\n\x03\x61sk\x18\x01 \x01(\t\"\x16\n\x05Haiku\x12\r\n\x05prose\x18\x01 \x01(\t2P\n\rProseAndBabel\x12?\n\x08GetHaiku\x12\x1b.proseandbabel.HaikuRequest\x1a\x14.proseandbabel.Haiku\"\x00\x62\x06proto3')
)




_HAIKUREQUEST = _descriptor.Descriptor(
  name='HaikuRequest',
  full_name='proseandbabel.HaikuRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ask', full_name='proseandbabel.HaikuRequest.ask', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=65,
)


_HAIKU = _descriptor.Descriptor(
  name='Haiku',
  full_name='proseandbabel.Haiku',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prose', full_name='proseandbabel.Haiku.prose', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['HaikuRequest'] = _HAIKUREQUEST
DESCRIPTOR.message_types_by_name['Haiku'] = _HAIKU
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HaikuRequest = _reflection.GeneratedProtocolMessageType('HaikuRequest', (_message.Message,), dict(
  DESCRIPTOR = _HAIKUREQUEST,
  __module__ = 'ProseAndBabel_pb2'
  # @@protoc_insertion_point(class_scope:proseandbabel.HaikuRequest)
  ))
_sym_db.RegisterMessage(HaikuRequest)

Haiku = _reflection.GeneratedProtocolMessageType('Haiku', (_message.Message,), dict(
  DESCRIPTOR = _HAIKU,
  __module__ = 'ProseAndBabel_pb2'
  # @@protoc_insertion_point(class_scope:proseandbabel.Haiku)
  ))
_sym_db.RegisterMessage(Haiku)



_PROSEANDBABEL = _descriptor.ServiceDescriptor(
  name='ProseAndBabel',
  full_name='proseandbabel.ProseAndBabel',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=91,
  serialized_end=171,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetHaiku',
    full_name='proseandbabel.ProseAndBabel.GetHaiku',
    index=0,
    containing_service=None,
    input_type=_HAIKUREQUEST,
    output_type=_HAIKU,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROSEANDBABEL)

DESCRIPTOR.services_by_name['ProseAndBabel'] = _PROSEANDBABEL

# @@protoc_insertion_point(module_scope)
